name: Build and Deploy Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Check JAR exists
      run: ls -l target/demo-0.0.1-SNAPSHOT.jar

    - name: Build Docker image
      run: docker build -t hello-springboot .

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag hello-springboot ${{ secrets.DOCKER_USERNAME }}/hello-springboot:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-springboot:latest
